#!/usr/bin/env bash
# Step `open_pr` - hand the artifact to the repo. When PIPELINE_REPO is set,
# copy artifacts onto a branch there and open a PR (branch + PR doctrine,
# never direct to master). Without it, the artifacts stay in the run dir and
# pr_url records that honestly - a dry run should not touch a repo.
set -euo pipefail
RUN="${WORKFLOW_RUN_DIR:-runs/latest}"
if [ -z "${PIPELINE_REPO:-}" ]; then
  echo "(local only - PIPELINE_REPO not set; artifacts at $RUN/artifacts)" > "$RUN/pr_url"
  echo "PR step skipped: PIPELINE_REPO not set. Artifacts remain at $RUN/artifacts"
  exit 0
fi
BRANCH="pipeline/emit-$(date +%Y%m%d%H%M%S)"
DEST="${PIPELINE_DEST:-generated}"
cd "$PIPELINE_REPO"
git checkout -b "$BRANCH"
mkdir -p "$DEST"
cp -r "$OLDPWD/$RUN/artifacts/." "$DEST/"
git add "$DEST"
git commit -m "pipeline: budgeted-emit artifact ($(basename "$RUN"))"
git push -u origin "$BRANCH"
gh pr create --title "Pipeline artifact: budgeted emit run" --body "Generated by the budgeted-emit pipeline. Plan, review, and per-chunk gates in the run directory. Review before merge." > "$RUN/pr_url"
cat "$RUN/pr_url"
